- name: 'Next Training Trajectory'
  service: 'assistive_controller/next_trajectory'
  column: 1
  service_type: 'Trigger'
- name: 'Reset Trajectory'
  service: 'assistive_controller/reset_trajectory'
  column: 1
  service_type: 'Trigger'
- name: 'No Assistance'
  service: 'assistive_controller/no_assist'
  column: 0
  service_type: 'SetBool'
  default_value: true
- name: 'Assistive Distance Model'
  service: 'assistive_controller/distance_assist'
  column: 0
  service_type: 'SetBool'
  default_value: false
- name: 'Assistive Tunnel Model'
  service: 'assistive_controller/tunnel_assist'
  column: 0
  service_type: 'SetBool'
  default_value: false